### ISSUE TITLE
Ho to use the BDX Ressources

### ISSUE THREAD

**Issue by yphil-dev** [SolarLune/SolHelp#1]
Hi; I'm really wondering what to do with the [bdxhelper ressources](https://github.com/SolarLune/SolHelp/tree/master/BDX/bdxhelper) when I try to launch the main jar file I get a 

```
#java -jar bdxhelper.jar 
no main manifest attribute, in bdxhelper.jar
```

So obviously I'm doing it wrong. How for instance, can I use the Flash component (seems ideal for a laser shot) in my BDX game?
In exchange for your guidance, I promise to update [the wiki](https://github.com/SolarLune/SolHelp/wiki) with what I learned ;) Oh BTW, the subreddit link is dead ;(

**Comment by SolarLune** [comment]
Hey, it should be as simple as putting it in the libs directory in your project folder and then importing and using it as usual. Here's an example using the default template blend file to make the G_Sacky object flash:

``` java
package com.solarlune.testgame;

import com.nilunder.bdx.*;
import com.solarlune.bdxhelper.components.Flash;
import javax.vecmath.Vector4f;

public class G_Sacky extends GameObject{

    public void init(){

        components.add(new Flash(this, new Vector4f(1, 1, 1, 1), new Vector4f(1, 0, 0, 1), 1.0f));
        //Or, if you want a simpler approach:
        components.add(new Flash(this, new Vector4f(1, 0, 0, 1)));

    }

}
```

I also added a State Machine and State to help out some basic AI a bit. And thanks, I fixed the broken link.

**Comment by yphil-dev** [comment]
Wow, that was quick! OK I tried that (`cp bdxhelper.jar ~/tmp/BDXDEV/daypatrol/core/libs
`) and it gave me:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsupportedClassVersionError: com/solarlune/bdxhelper/components/Flash : Unsupported major.minor version 52.0
```

Is there something I should check? I'm using BDX 0.1.3 and a javac 1.7.0_75 in Blender 2.74RC3

EDIT now this is what I have on top of my file:

```
package org.opensimo.daypatrol;
import com.nilunder.bdx.*;
import org.opensimo.bdxhelper.components.Flash;
```

And now it says

`error: package org.opensimo.bdxhelper.components does not exist` I feel I'm close :p

**Comment by SolarLune** [comment]
I built it with Java 8, so that's probably it. Try upgrading your Java, or just copy the component's source file into your own project if you want just that element.

**Comment by yphil-dev** [comment]
>  Try upgrading your Java, or just copy the component's source file into your own project if you want just that element.

Both suggestions worked, thanks! (Only I can't see the effect, but that may be because I'm using it on a regular object with no texture... Also I was wondering, what about particles in BDX/LibGDX? Well, no real ones, just someting similar to your wonderful XEmitter system (that I abused of in [my latest game](https://www.indiegogo.com/projects/go-go-speed-racer/) for both exhausts and celebration fireworks)

And finally (while we're at it ;p) how would one implement [a GLSL shader effect](http://glslsandbox.com/) in BDX?

**Comment by SolarLune** [comment]
Weird, I thought I replied to this.

Anyway, thanks for using X-Emitter. I don't know if Goran has any plans to support particles as a special object in BDX, or to integrate Blender's particle creation tools in BDX in some way. For now, you'll have to do particles by hand in code.

As for the object not visibly updating, I'm not sure why that is; do you have a material on the object, and did you add the Flash component to an object's component list? If you can't figure it out, posting a blend file example may be helpful. EDIT: Oh, and the Sacky object in the template example is invisible; the G_Sacky object is the visible "sprite".

As for 2D filters, BDX now supports this under the new [Filter](https://github.com/GoranM/bdx/wiki/API-Filter) class. A Filter is created with the vertex and fragment shaders you want (either in strings or from files). After that, you add the Filter to the scene's filters stack. I don't think it'll be a straight "port" to take filters from GLSLSandbox and put them in BDX, but it shouldn't be much trouble at all to make one work. 

One thing I see sometimes in those shaders is a resolution vector, but I don't quite see the point of it, since the screen increases from 0,0 to 1,1 and the texture sampling process works the same way (e.g. checking if if the texture coordinate's x value is less than 0.5 will allow you to target the left half of the screen). Anyway, if you need it, you can pass that uniform yourself.
